/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.austral.dissis.chess

import edu.austral.dissis.chess.gui.CachedImageResolver
import edu.austral.dissis.chess.gui.DefaultImageResolver
import edu.austral.dissis.chess.gui.GameView
import edu.austral.dissis.client.MyClient
import javafx.application.Application
import javafx.application.Application.launch
import javafx.scene.Scene
import javafx.stage.Stage

fun main() {
    launch(GameApplication::class.java)
}

class GameApplication : Application() {
    private val imageResolver = CachedImageResolver(DefaultImageResolver())

    companion object {
        const val GAMETITLE = "Chess"
        val myClient = MyClient()
    }

    override fun start(primaryStage: Stage) {
        primaryStage.title = GAMETITLE

        val root = GameView(imageResolver)
        primaryStage.scene = Scene(root)

        myClient.start(root)

        primaryStage.show()
    }
}